const generateReportHTML = (data, period) => {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body { font-family: 'Helvetica', sans-serif; color: #333; padding: 20px; }
            .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #1890ff; padding-bottom: 10px; }
            .logo { font-size: 24px; font-weight: bold; color: #1890ff; }
            .title { font-size: 20px; margin-top: 10px; font-weight: bold; }
            .meta { font-size: 14px; color: #666; margin-top: 5px; }
            
            .summary-cards { display: flex; justify-content: space-between; margin-bottom: 30px; }
            .card { flex: 1; padding: 15px; background: #f8f9fa; border-radius: 8px; margin: 0 5px; text-align: center; }
            .card-title { font-size: 12px; color: #888; text-transform: uppercase; }
            .card-value { font-size: 18px; font-weight: bold; margin-top: 5px; }
            
            .section-title { font-size: 16px; font-weight: bold; border-bottom: 1px solid #eee; padding-bottom: 5px; margin-bottom: 15px; margin-top: 30px; }
            
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px; }
            th { text-align: left; background: #f0f2f5; padding: 10px; border-bottom: 1px solid #ddd; }
            td { padding: 10px; border-bottom: 1px solid #eee; }
            
            .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #aaa; border-top: 1px solid #eee; padding-top: 10px; }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="logo">MEDILINK PHARMACY</div>
            <div class="title">Financial Report</div>
            <div class="meta">Period: ${period.start} to ${period.end}</div>
            <div class="meta">Generated: ${new Date().toLocaleString()}</div>
        </div>

        <div class="summary-cards">
            <div class="card">
                <div class="card-title">Total Revenue</div>
                <div class="card-value" style="color: #3f8600">ETB ${data.totalRevenue?.toFixed(2)}</div>
            </div>
            <div class="card">
                <div class="card-title">Net Income</div>
                <div class="card-value" style="color: #1890ff">ETB ${data.netIncome?.toFixed(2)}</div>
            </div>
            <div class="card">
                <div class="card-title">Total Refunds</div>
                <div class="card-value" style="color: #cf1322">ETB ${data.totalRefunds?.toFixed(2)}</div>
            </div>
        </div>

        <div class="summary-cards">
            <div class="card">
                <div class="card-title">Successful Txns</div>
                <div class="card-value">${data.successCount}</div>
            </div>
            <div class="card">
                <div class="card-title">Failed Txns</div>
                <div class="card-value" style="color: red">${data.failedCount}</div>
            </div>
            <div class="card">
                <div class="card-title">Avg Order Value</div>
                <div class="card-value">ETB ${data.avgOrderValue?.toFixed(2)}</div>
            </div>
        </div>

        <div class="section-title">Payment Method Breakdown</div>
        <table>
            <thead>
                <tr>
                    <th>Method</th>
                    <th>Count</th>
                    <th>Reference</th>
                </tr>
            </thead>
            <tbody>
                ${Object.entries(data.methodBreakdown || {}).map(([method, count]) => `
                <tr>
                    <td style="text-transform: capitalize">${method}</td>
                    <td>${count}</td>
                    <td>-</td>
                </tr>
                `).join('')}
                ${Object.keys(data.methodBreakdown || {}).length === 0 ? '<tr><td colspan="3">No data available</td></tr>' : ''}
            </tbody>
        </table>

        <div class="footer">
            Generated by Medilink System | Authorized Personnel Only
        </div>
    </body>
    </html>
    `;
};

module.exports = { generateReportHTML };
